### ISSUE TITLE
When there are multiple audio tracks in a video, selecting audio tracks does not work

### ISSUE THREAD

**Issue by simear2004** [sammoth/foo_mpv#5]
When there are multiple audio tracks in a video, selecting audio tracks does not work
For example, movies with English, French, Japanese and other audio tracks cannot be switched to the language they want

**Comment by sammoth** [comment]
This component doesn't handle audio playback at all, the audio is handled entirely by foobar and its input components. There is an option to switch audio track for some filetypes in the context menu, eg. right clicking on the item in the playlist view, but it may not work for some filetypes or input components.
